version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - "ThibautHH"
    reviewers:
      - "ThibautHH"
    commit-message:
      prefix: "deps(dev): "
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - "dependencies/github-actions"
